# Generated by Django 4.1.1 on 2023-03-21 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BranchOffice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Name Branch Office"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Registration date"
                    ),
                ),
            ],
            options={
                "verbose_name": "BranchOffice",
                "verbose_name_plural": "BranchOffices",
                "db_table": "branchOffice",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                (
                    "phone_number",
                    models.CharField(max_length=50, verbose_name="Phone number"),
                ),
                (
                    "email_address",
                    models.EmailField(max_length=30, verbose_name="Email address"),
                ),
                ("address", models.CharField(max_length=250, verbose_name="Address")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Registration date"
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "db_table": "supplier",
                "ordering": ["date_created"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Product")),
                (
                    "description",
                    models.CharField(max_length=250, verbose_name="Description"),
                ),
                ("stock", models.PositiveIntegerField(verbose_name="Stock")),
                ("purchase_price", models.FloatField(verbose_name="Purchase price")),
                ("selling_price", models.FloatField(verbose_name="Selling price")),
                ("industry", models.CharField(max_length=50, verbose_name="Industry")),
                (
                    "assurance_months",
                    models.PositiveIntegerField(verbose_name="Assurance months"),
                ),
                (
                    "marca",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="Marca"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="productos/",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "bar_code",
                    models.ImageField(
                        null=True,
                        upload_to="productos/barcode/",
                        verbose_name="Bar code",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Registration date"
                    ),
                ),
                (
                    "branchOffice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.branchoffice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "product",
                "ordering": ["date_created"],
            },
        ),
    ]
