# Generated by Django 4.1.1 on 2022-11-14 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nombre")),
                ("contacto", models.CharField(max_length=50, verbose_name="Contacto")),
                ("correo", models.EmailField(max_length=30, verbose_name="Correo")),
                (
                    "direccion",
                    models.CharField(max_length=250, verbose_name="Direccion"),
                ),
                ("estado", models.BooleanField(default=True)),
                (
                    "date_created",
                    models.DateField(auto_now_add=True, verbose_name="Registro"),
                ),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "db_table": "supplier",
                "ordering": ["date_created"],
            },
        ),
        migrations.CreateModel(
            name="Sede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Sede"),
                ),
                ("estado", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date_Created"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sede",
                "verbose_name_plural": "Sedes",
                "db_table": "sede",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Product")),
                (
                    "description",
                    models.CharField(max_length=250, verbose_name="Descripcion"),
                ),
                ("stock", models.PositiveIntegerField(verbose_name="Cantidad")),
                ("preciocompra", models.FloatField(verbose_name="Precio de Compra")),
                ("precioventa", models.FloatField(verbose_name="Precio venta")),
                (
                    "industria",
                    models.CharField(max_length=50, verbose_name="Industria"),
                ),
                ("garantia", models.PositiveIntegerField(verbose_name="Garantia")),
                ("marca", models.CharField(max_length=60, verbose_name="Marca")),
                ("estado", models.BooleanField(default=True)),
                (
                    "date_created",
                    models.DateField(auto_now_add=True, verbose_name="Registro"),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.supplier",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.sede",
                    ),
                ),
                (
                    "users",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Productos",
                "db_table": "producto",
                "ordering": ["date_created"],
            },
        ),
    ]
