# Generated by Django 4.1.1 on 2022-11-14 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetalleEgreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.PositiveIntegerField(verbose_name="Cantidad")),
            ],
            options={
                "db_table": "detalle_egreso",
            },
        ),
        migrations.CreateModel(
            name="Egreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Registro"
                    ),
                ),
                (
                    "detalle_egresos",
                    models.ManyToManyField(
                        through="almacen.DetalleEgreso", to="inventory.producto"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="detalleegreso",
            name="egreso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="almacen.egreso"
            ),
        ),
        migrations.AddField(
            model_name="detalleegreso",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.producto"
            ),
        ),
    ]
