# Generated by Django 4.1.1 on 2023-03-17 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0003_remove_product_supplier_alter_product_marca"),
    ]

    operations = [
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt_type",
                    models.CharField(max_length=250, verbose_name="Receipt type"),
                ),
                (
                    "serial_number",
                    models.PositiveIntegerField(verbose_name="Serial number"),
                ),
                ("total_amount", models.FloatField(verbose_name="Total amount")),
                ("income_tax", models.FloatField(verbose_name="Income tax")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Registration date"
                    ),
                ),
            ],
            options={
                "verbose_name": "Income",
                "verbose_name_plural": "Incomes",
                "db_table": "income",
                "ordering": ["date_created"],
            },
        ),
        migrations.CreateModel(
            name="SaleDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="quantity")),
                ("unit_price", models.FloatField(verbose_name="unit price")),
                ("discount", models.FloatField(verbose_name="discount")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sale Detail",
                "verbose_name_plural": "Sale Detail",
                "db_table": "sale_detail",
            },
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt_type",
                    models.CharField(max_length=250, verbose_name="Receipt type"),
                ),
                (
                    "serial_number",
                    models.PositiveIntegerField(verbose_name="Serial number"),
                ),
                ("sale_price", models.FloatField(verbose_name="Sale price")),
                ("buy_price", models.FloatField(verbose_name="Buy price")),
                ("sale_tax", models.FloatField(verbose_name="Sale tax")),
                ("sale_total", models.FloatField(verbose_name="Sale total")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Registration date"
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        through="sales.SaleDetail", to="inventory.product"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sale",
                "verbose_name_plural": "Sales",
                "db_table": "sale",
                "ordering": ["date_created"],
            },
        ),
        migrations.AddField(
            model_name="saledetail",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sales.sales"
            ),
        ),
        migrations.CreateModel(
            name="IncomeDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="quantity")),
                ("amount", models.FloatField(verbose_name="amount")),
                (
                    "income",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sales.income"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Income Detail",
                "verbose_name_plural": "Income Detail",
                "db_table": "income_detail",
            },
        ),
        migrations.AddField(
            model_name="income",
            name="products",
            field=models.ManyToManyField(
                through="sales.IncomeDetail", to="inventory.product"
            ),
        ),
        migrations.AddField(
            model_name="income",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.supplier"
            ),
        ),
    ]
